apiVersion: v1
kind: ResourceQuota
metadata:
  name: ai-stack-quota
  namespace: ai-stack
spec:
  hard:
    requests.cpu: "8"
    requests.memory: "16Gi"
    limits.cpu: "16"
    limits.memory: "32Gi"
    requests.nvidia.com/gpu: "2"
    pods: "20"
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: ai-stack-limits
  namespace: ai-stack
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      max:
        cpu: "4"
        memory: "8Gi"
    - type: Pod
      max:
        cpu: "8"
        memory: "16Gi"
