apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-pipeline-documents
  namespace: ai-stack
  labels:
    app: rag-pipeline
    component: pipeline
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
